import numpy as np
m1=np.array([[3,0,1],[3,3,2],[3,2,1]])
m2=np.array([[5,0,1],[1,0,3],[6,3,4]])
print ("Original 3D matrix : ")
print (m1)
print (m2)
print ("Sum of matrix : ")
a = np.add(m1,m2)
print(a)
print ("Difference of matrix : ")
s=np.subtract(m1,m2)
print (s)
print ("Product of matrix : ")
p = np.multiply(m1,m2)
print(p)
